sudo: required
services:
  - docker

before_install:
  - docker build -t demirtasdurmus/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true demirtasdurmus/frontend npm run test -- --coverage

language: generic
