version: '3.4'

services:
  web:
    image: web
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: test
    volumes:
      - /app/node_modules
      - .:/app
    command: [ "npm", "run", "test" ]
